- CONTRIBUTING.md
A simple contributing model.. as it is, it works.
> add init contrib doc

- src/main.rs
If date is empty from `frontmatter` we enter in a way to grab the alternative date and slug.
The slug itself is always returned from the `get_slug`, so this is a deviation in case the date is empty.
- Closes
- #23 
Example: `2025-05-01-another-blog-post.md`
> Extract date from filename

- Cargo.toml
- example/marmite.yaml
- example/templates/base.html
- example/templates/content.html
- example/templates/list.html
- src/main.rs
- src/tera_functions.rs
> feat: add url_for

- .github/workflows/main.yml
- example/content/second-blog-post.md
- example/marmite.yaml
- example/templates/group.html
- src/config.rs
- src/main.rs
> feat: render tags

- example/templates/content.html
- example/templates/group.html
- example/templates/list.html
- src/content.rs
- src/main.rs
- src/markdown.rs
- src/site.rs
- src/tera_functions.rs
> feat: slugify filter and modularization

- Cargo.toml
- example/content/first-blog-post.md
- justfile
- src/markdown.rs
Enabled most common markdown extensions on Comrak
> feat: Enabled markdown extensions

- .github/workflows/main.yml
- CONTRIBUTING.md
- justfile
- src/server.rs
- src/site.rs
> Clippy magic

- src/main.rs
- src/site.rs
follow up on @SkySingh04  work
make `--watch --serve` to work
> feat: Watch and serve

- Cargo.lock
- example/templates/group.html
- src/site.rs
> misc: list content on group pages

- example/content/2024-10-19-what-is-marmite-static-site-generator.md
- example/content/customizing-templates.md
- example/templates/content.html
- src/content.rs
- src/markdown.rs
- src/site.rs
- src/tera_functions.rs
If not defined on frontmatter, card image will be extracted from the first image on the html content
> feat: extract card image from html if not defined

- .gitignore
- Cargo.lock
- Cargo.toml
- example/content/customizing-templates.md
- example/templates/group.html
- example/templates/list.html
- src/content.rs
- src/markdown.rs
- src/site.rs
- src/tera_functions.rs
Make tags and archive available on all templates
fix #117 and discussion #116 by @DuckerQA
WARNING: Breaking change! the group.html template must be updated.
> feat(breaking): Global groups

- example/static/marmite.css
- example/templates/content.html
- example/templates/list.html
- object cover banner responsive 
- content-authors css ajusts 
- list.html author profile css
> fix: css banner, content-author and author profile

- example/content/2023-01-01-pagination.md
- example/content/2024-10-19-what-is-marmite-static-site-generator.md
- example/content/2024-11-14-hello-streams.md
- example/templates/group.html
- src/config.rs
- src/content.rs
- src/markdown.rs
- src/site.rs
- src/tera_functions.rs
> feat: Stream of content

- example/content/2024-10-24-getting-started.md
- example/templates/list.html
- src/cli.rs
- src/config.rs
- src/content.rs
- src/main.rs
- src/site.rs
> Generate config

- Cargo.lock
- Cargo.toml
- example/templates/base.html
- src/feed.rs
- src/main.rs
- src/site.rs
> feat: RSS feeds

- .github/marmite.yaml
- example/marmite.yaml
- src/cli.rs
- src/config.rs
- src/feed.rs
- src/site.rs
> feat: generate JSON feeed

- Cargo.lock
- Cargo.toml
- src/markdown.rs
- src/site.rs
> Gotta go fast

- example/content/2023-01-01-pagination.md
- src/cli.rs
- src/config.rs
- src/content.rs
- src/site.rs
> feat: incremental build, using modified timestamp

- src/parser.rs
Fix internal links with heading not working by modifying the regex to consider links ending with `#{heading}` and adding the heading to the heading to the resulting link.
Fixes #208
> Fix internal links with heading not working

- example/marmite.yaml
- src/site.rs
Add functionality to check option static_folders in config file and copy folders to site
For issue #207
> Add support for extra static folders in configuration

- example/content/2024-10-24-21-05-12-getting-started.md
Add instructions for installing on ArchLinux via AUR and FreeBSD.
> docs: installing on ArchLinux and FreeBSD

- src/feed.rs
Fix for RSS feed by assuring a compliant URL. 
Build tested on my blog: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fcbernardino.dev%2Findex.rss
PS: The recommendation about the description may be due to my posts don't have them
Closes: #168
> bugfix: Fix RSS feed generation with compliant URL.

- example/content/showcase.md
Fixes a broken a link to Code World Showcase in showcase.md
> Fixes a broken link

- example/content/2024-11-26-marmite-command-line-interface.md
- example/content/customizing-templates.md
- example/templates/content.html
- src/cli.rs
- src/config.rs
- src/content.rs
- src/site.rs
This PR implements issue #225, adding next and previous post links to content pages.
**NOTE**: PR Automatic created by Gemini-CLI
Closes #225
> feat: Add next and previous post links

- README.md
- example/content/2024-10-24-21-05-12-getting-started.md
- Added Homebrew installation method with link to formula  
- Added Arch Linux AUR installation with link to package
- Added FreeBSD installation with link to port
- Updated both README.md and getting-started documentation
Closes #316
> docs: Add more installation sources
