rochacbruno/marmite

example/static/github-dark.min.css, example/static/github-light.min.css, example/static/highlight.min.js, example/static/theme-switcher.js, example/templates/base.html
Added `Highlight.js` to the `base.html` template inside `example`.
As default color left the same as `github`uses (both light and dark themes).
Only one problem related to compatibility between `pico` and `highlight.js`... had to edit the `github-light.min.css` background-color, because it's taking precedence instead of pico.
Basically from:
```css
.hljs{color:#24292e;background:#fff}
```
to
```css
.hljs{color:#24292e;background:#f6f6f6}
```
---
> **Please let me know if any tweaks need it.**
- Closes
- #4  
Uploading marmite-2024-10-17_22.44.08.mp4…
=> Add syntax highlight

src/cli.rs, src/main.rs, src/server.rs
Added the CLI entry for `--bind`
- Closes
- #33
=> Accept host and port as CLI arguments when --serve is used

src/server.rs
```bash
[2024-10-22T09:50:26Z INFO  marmite] Starting built-in HTTP server...
[2024-10-22T09:50:26Z INFO  marmite::server] Server started at http://localhost:8000/ - Type ^C to stop.
[2024-10-22T09:50:28Z INFO  marmite::server] "GET index.html HTTP/1.1" 200 -
[2024-10-22T09:50:29Z INFO  marmite::server] "GET about.html HTTP/1.1" 200 -
[2024-10-22T09:50:32Z INFO  marmite::server] "GET index.html HTTP/1.1" 200 -
[2024-10-22T09:50:33Z INFO  marmite::server] "GET pages.html HTTP/1.1" 200 -
[2024-10-22T09:50:33Z INFO  marmite::server] "GET tags.html HTTP/1.1" 200 -
[2024-10-22T09:50:38Z ERROR marmite::server] "GET sdfsdfsd.html HTTP/1.1" 404 -
[2024-10-22T09:50:44Z ERROR marmite::server] "GET dfsfsdfsdfsdf.html HTTP/1.1" 404 -
```
=> chore: more messages on HTTP server

example/content/404.md, example/templates/base.html, src/markdown.rs, src/server.rs, src/site.rs
Add new rendering process to consider page 404 generation.
This generation is following a process to ignore _slug_ frontmatter for this page and use the proper _md_ name file to generate the html.
It also considers that page 404.md can be deleted and if it happen a default 404.html will be generated.
Closes #9
=> Render page 404

.github/marmite.yaml, README.md, example/content/customizing-templates.md, example/content/enabling-comments.md, example/marmite.yaml, example/templates/comments.html, example/templates/content.html, src/config.rs
To follow the same naming used on front-matter for content
=> misc: Rename site.data to site.extra

src/cli.rs, src/main.rs, src/templates.rs
This PR introduces two new flags, `--init-templates` and `--start-theme`, to the Marmite CLI, allowing users to initialize project templates and themes more easily. The new flags add the following functionality:
- **`--init-templates`**: Creates a `templates/` folder in the output directory, adding a `base.html` file as a starter template.
- **`--start-theme`**: Extends the `--init-templates` command by additionally creating a `static/` folder with placeholder files (`style.css`, `script.js`) referenced by the templates.
To support these new flags, two functions were added:
- **`initialize_templates`**: Sets up the `templates` directory and base files.
- **`initialize_theme_assets`**: Sets up the `static` assets directory and initial CSS/JS files.
Both functions are currently in a new …
=> Add `--init-templates` and `--start-theme` Flags 

.github/marmite.yaml, example/content/2024-10-19-what-is-marmite-static-site-generator.md, example/content/customizing-templates.md, example/static/marmite.css, example/static/marmite.js, example/templates/base.html, example/templates/content.html, example/templates/group.html, example/templates/list.html, example/templates/pagination.html, src/config.rs, src/site.rs
=> Pagination

example/templates/list.html
This should fix the bug raised by #84 
I tryed to leave as a minimal change ... change could be done inside `site.rs` but was more convoluted given this would need to happen before Tera convert everything to html, but it would be problematic for the content. It would probably need a new property on the Struct just for that.
Closes:
- #84
=> Repeated title annoyance

example/content/markdown-format.md, example/templates/list.html, src/content.rs, src/markdown.rs, src/site.rs
@rochacbruno this an attempt to make it possible the `description` for the cards in the `list.html`.
I added a `description` to the `Content` struct, that could get filled with values in a `description`, if None we just fallback to the previous way (get from html and strip everything).
=> Cards description

example/static/marmite.css
I was checking changes [here](https://github.com/rochacbruno/marmite/pull/105), and notice that the background was set to `white` which broke theme style...
Also did small adjustment to center the `X` on close button.
And remove extra space from some classes...
=> Small css tweak to fix theme

example/static/marmite.css
Before (loading hljs lazily will override color)
Now
=> fix: Light mode code background fix

example/marmite.yaml, example/templates/list.html, src/config.rs, src/main.rs, src/site.rs, src/tera_filter.rs
Addressing #82, I added a filter called `default_date_format` that allows users to add their default date format. The default date can be configured in `marmite.yaml` with key `default_date_format`.
This is my first contribution, any feedback is appreciated
=> feat: add default date format

example/templates/base.html, src/site.rs
render list pages from stream-1.html to stream-n.html
if a page named {stream}.md is found on content folder, this is considered the index ex: index.md, notes.md, pages.md, tags-foo.md
if that page is not found, renders a {stream}.html mirroring {stream}-1.html
=> feat:allow  overriding any listing page via markdown

src/content.rs, src/site.rs
Add "comments" attribute to frontmatter in order to disable comments for a specific page.
For ticket #199
=> Add "comments" attribute

.github/marmite.yaml, example/content/2024-10-24-21-05-12-getting-started.md, example/content/2024-11-26-marmite-command-line-interface.md, example/marmite.yaml, example/templates/content.html, src/cli.rs, src/config.rs
Add new flag to enable/disable related content and back links for a post.
Defaults to true.
For issue #192
=> feat: Add enable_related_content flag

src/feed.rs
The logic used to say if the string does not contain `https://` **or** `https://` — it should be **and** instead because full URLs would have one or the other ; )
(Plus minor change to use `.starts_with` instead of just `contains`)
=> Fix feed URL (duplicated `http://`)

src/site.rs
I wrote a small fix to ignore the output folder upon rebuilding event.
Hope this helps.
=> Fixes #258 by ignoring the generated folder

example/content/2024-10-30-python-tutorial-part-1.md, example/content/2024-11-05-python-tutorial-part-2.md, example/content/2024-11-12-python-tutorial-part-3.md, example/content/2025-01-22-series-feature.md, example/marmite.yaml, example/templates/base_feeds.html, example/templates/content.html, example/theme_template/templates/content.html, src/config.rs, src/content.rs, src/site.rs, src/tera_functions.rs
- Implements Series feature allowing content to be grouped into ordered collections
- Adds support for series frontmatter field and configuration
- Closes #102
- Added series support to content structure and parsing
- Created dedicated series pages with chronological ordering
- Implemented series index page showing all available series
- Added series navigation with precedence over stream navigation
- Generated RSS and JSON feeds for each series
- Updated templates to display series links and handle related content
- Fixed series feed URL generation (from `serie-` to `series-` prefix)
- Added comprehensive example content with Python tutorial series
- Created documentation post explaining the feature
- All tests pass (`cargo test`)
- Code quality checks pass (`mask check`, `mask …
=> feat: implement Series feature for grouping related content

example/content/2025-07-10-20-31-29-configuration-reference.md, example/content/2025-08-01-shortcodes-guide.md, src/cli.rs, src/config.rs, src/main.rs, src/shortcodes.rs, src/site.rs, src/tests/main.rs, tests/basic_functionality.rs, tests/content_generation.rs, tests/features.rs, tests/streams.rs, tests/themes.rs
This PR fixes issue #338 where embedded/built-in shortcodes were not being loaded when a site didn't have a `shortcodes` directory.
When users ran `marmite myblog --shortcodes` on a site without a shortcodes directory, the list of available shortcodes was empty. Additionally, embedded shortcodes like `` were not being processed during site generation.
- Modified `ShortcodeProcessor::collect_shortcodes()` to always load built-in/embedded shortcodes first, before checking if the user's shortcodes directory exists
- Fixed type mismatch when passing shortcode processor reference to `handle_content_pages()`
- Updated documentation to clarify that built-in shortcodes are always available
Tested with the reproducer from issue #338:
```bash
$ marmite myblog --init-site
$ marmite myblog …
```
=> fix: embedded shortcodes not being loaded when no shortcodes directory exists

example/content/2025-07-10-20-31-29-configuration-reference.md, example/content/2025-08-01-shortcodes-guide.md, src/cli.rs, src/content.rs, src/main.rs, src/parser.rs, src/re.rs, src/shortcodes.rs, src/site.rs, src/tests/shortcodes.rs
- Created `src/re.rs` module containing all regex pattern constants
- Replaced hardcoded regex patterns across the codebase with centralized constants
- Added comprehensive documentation for each pattern
- **New file**: `src/re.rs` - Contains 14 regex pattern constants with documentation
- **Updated modules**: 
- `src/site.rs` - HTML/template tag patterns
- `src/parser.rs` - Link and heading extraction patterns
- `src/shortcodes.rs` - Shortcode and macro patterns
- `src/content.rs` - Date, stream, and slugify patterns
- `src/main.rs` - Added module declaration
- **Maintainability**: All regex patterns in one place
- **Documentation**: Each pattern has clear comments explaining its purpose
- **Consistency**: Ensures patterns are used consistently across the codebase
- **Readability**: …
=> refactor: centralize regex patterns in dedicated module

src/content.rs, src/tests/content.rs, src/tests/image_provider.rs
This PR fixes a bug where the media folder name was hardcoded to `"media"` instead of using the configurable `media_path` value from the site configuration.
The `find_matching_file` function in `content.rs` was using a hardcoded `"media"` string instead of respecting the user's configured `media_path` setting in `marmite.yaml`.
- Pass `media_path` from site configuration through the function chain
- Update `get_card_image` and `get_banner_image` functions to accept the `media_path` parameter
- Fix recursive call to `get_banner_image` within `get_card_image`
- Update all related tests to pass the media_path parameter
- Modified `src/content.rs`:
- Updated function signatures to accept `media_path` parameter
- Replaced hardcoded `"media"` with configurable value
- Modified …
=> fix: use media_path from config instead of hardcoded value

example/marmite.yaml, example/static/marmite.js, example/templates/base.html
Add extra/colormode to the marmite.yaml settings that can be "auto", "dark" or "light" to set a preferred theme style when the page is loaded.
If a user toggles the scheme on the page, their setting is saved to their local storage and on next page load the config setting is ignored. The config setting is only ignored if the local storage value is not "auto"
A new setting `colormodetogggle` which accepts a boolean is added that allows the user to enable/disable the colormode toggle in the header of the page, fixing the page to the color set (either by system or by config)
Fixes #200
=> Add preferred theme scheme option
